<a href="https://colab.research.google.com/github/garbuzovan496-debug/datalens-sales-dashboard/blob/main/AI_Ticket_Router.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")
import sys
print(sys.version)

Hello
3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [ ]:
# Установка всех необходимых библиотек
!pip install -q torch transformers datasets pandas numpy scikit-learn kagglehub accelerate gradio tqdm matplotlib seaborn nltk

print("✅ Все библиотеки установлены!")

✅ Все библиотеки установлены!

In [ ]:
# Создание папок для проекта
import os
from pathlib import Path

# Создаём все нужные папки
folders = ['data', 'models', 'src', 'web_demo', 'logs', 'presentation']

for folder in folders:
    Path(folder).mkdir(exist_ok=True)
    print(f"✅ Создана папка: {folder}")

print("\n📁 Структура проекта готова!")
print("📂 Папки созданы:", ', '.join(folders))

✅ Создана папка: data
✅ Создана папка: models
✅ Создана папка: src
✅ Создана папка: web_demo
✅ Создана папка: logs
✅ Создана папка: presentation

📁 Структура проекта готова!
📂 Папки созданы: data, models, src, web_demo, logs, presentation

In [ ]:
# Скачивание датасета с Kaggle
import kagglehub
import shutil
import pandas as pd
from pathlib import Path

print("🔄 ЗАГРУЗКА ДАТАСЕТА С KAGGLE")
print("="*50)
print("⏳ Пожалуйста, подождите...")

try:
    # Скачиваем датасет
    path = kagglehub.dataset_download("saurav9786/multilingual-customer-support-tickets")
    print(f"✅ Датасет скачан в: {path}")

    # Копируем файлы в папку data
    data_dir = Path("data")
    files_copied = []

    for file in Path(path).glob("*"):
        if file.is_file():
            dest = data_dir / file.name
            shutil.copy2(file, dest)
            files_copied.append(file.name)
            print(f"   📄 Скопирован: {file.name}")

    # Проверяем загрузку
    csv_files = list(data_dir.glob("*.csv"))
    if csv_files:
        df = pd.read_csv(csv_files[0])
        print("\n" + "="*50)
        print("✅ ДАТАСЕТ УСПЕШНО ЗАГРУЖЕН!")
        print("="*50)
        print(f"📊 Строк: {len(df):,}")
        print(f"📊 Колонок: {len(df.columns)}")
        print(f"📋 Колонки: {', '.join(list(df.columns)[:8])}")

        # Показываем первые строки
        print("\n📝 Первые 3 строки:")
        print(df.head(3).to_string())
    else:
        print("⚠️ CSV файлы не найдены")

except Exception as e:
    print(f"❌ Ошибка: {e}")
    print("\n📝 Альтернативный способ:")
    print("1. Зайдите на: https://www.kaggle.com/datasets/saurav9786/multilingual-customer-support-tickets")
    print("2. Нажмите 'Download'")
    print("3. Распакуйте архив в папку data/")

🔄 ЗАГРУЗКА ДАТАСЕТА С KAGGLE
==================================================
⏳ Пожалуйста, подождите...
❌ Ошибка: 403 Client Error.

You don't have permission to access resource at URL: https://api.kaggle.com/v1/datasets.DatasetApiService/GetDataset. Please make sure you are authenticated if you are trying to access a private resource or a resource requiring consent.

📝 Альтернативный способ:
1. Зайдите на: https://www.kaggle.com/datasets/saurav9786/multilingual-customer-support-tickets
2. Нажмите 'Download'
3. Распакуйте архив в папку data/

In [ ]:
# ЗАГРУЗКА ДАТАСЕТА В COLAB
from google.colab import files
import zipfile
import pandas as pd
from pathlib import Path

print("📤 ЗАГРУЗКА ДАТАСЕТА В COLAB")
print("="*50)
print("1. Нажмите 'Выбрать файл'")
print("2. Выберите скачанный архив (archive.zip или похожий)")
print("3. Дождитесь загрузки")
print("="*50)

# Загружаем файл
uploaded = files.upload()

# Находим ZIP файл
zip_files = [f for f in uploaded.keys() if f.endswith('.zip')]

if zip_files:
    zip_path = zip_files[0]
    print(f"\n✅ Файл загружен: {zip_path}")

    # Создаём папку data
    Path("data").mkdir(exist_ok=True)

    # Распаковываем
    print("📦 Распаковка...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall('data/')

    print("✅ Распаковано в папку data/")

    # Проверяем
    csv_files = list(Path("data").glob("*.csv"))

    if csv_files:
        df = pd.read_csv(csv_files[0])
        print("\n" + "="*50)
        print("✅ ДАТАСЕТ ЗАГРУЖЕН!")
        print("="*50)
        print(f"📊 Строк: {len(df):,}")
        print(f"📊 Колонок: {len(df.columns)}")
        print(f"📋 Колонки: {list(df.columns)}")
        print("\n📝 Первые 3 строки:")
        print(df.head(3))
    else:
        print("⚠️ CSV файлы не найдены")
        print("📂 Содержимое папки data:")
        for f in Path("data").iterdir():
            print(f"   - {f.name}")
else:
    print("❌ ZIP файл не найден")

📤 ЗАГРУЗКА ДАТАСЕТА В COLAB
==================================================
1. Нажмите 'Выбрать файл'
2. Выберите скачанный архив (archive.zip или похожий)
3. Дождитесь загрузки
==================================================

Saving archive.zip to archive.zip

✅ Файл загружен: archive.zip
📦 Распаковка...
✅ Распаковано в папку data/

==================================================
✅ ДАТАСЕТ ЗАГРУЖЕН!
==================================================
📊 Строк: 2,125
📊 Колонок: 5
📋 Колонки: ['subject', 'body', 'queue', 'priority', 'language']

📝 Первые 3 строки:
                                             subject  \
0  Dringend: Fehler bei der Zahlungsabwicklung de...
1                           Build-Fehler aufgetreten
2       Aktualisierung zur HIPAA-Konformität für CMS

                                                body  \
0  Liebes Support-Team, ich kontaktiere Sie im Na...
1  Hallo Support-Team, wir haben gelegentlich Bui...
2  Liebes Support-Team, ich benötige Unterstützun...

                          queue priority language
0  Account & Billing Management     high       de
1          Software Development   medium       de
2   Legal & Compliance Requests      low       de

In [ ]:
# ============================================================
# ОБУЧЕНИЕ МОДЕЛИ КЛАССИФИКАЦИИ ЗАЯВОК
# ============================================================
print("🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ")
print("="*50)
print("⏳ Это займёт 20-30 минут...")

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
from datasets import Dataset
import torch
import warnings
warnings.filterwarnings('ignore')

# 1. ЗАГРУЗКА ДАННЫХ
print("\n📊 1. Загрузка данных...")
csv_files = list(Path("data").glob("*.csv"))
df = pd.read_csv(csv_files[0])

# 2. ПОДГОТОВКА ДАННЫХ
print("📝 2. Подготовка текстов...")

# Объединяем subject и body в один текст
df['text'] = df['subject'].fillna('') + ' ' + df['body'].fillna('')

# Удаляем пустые строки
df = df[df['text'].str.len() > 10]

# Удаляем строки без категории
df = df.dropna(subset=['queue'])

print(f"   Осталось строк: {len(df):,}")

# 3. КОДИРОВАНИЕ КАТЕГОРИЙ
print("🏷️ 3. Кодирование категорий...")
le = LabelEncoder()
y = le.fit_transform(df['queue'])
X = df['text'].values

print(f"   Количество категорий: {len(le.classes_)}")
print(f"   Категории: {list(le.classes_)[:5]}...")

# 4. РАЗБИВКА НА ОБУЧЕНИЕ И ТЕСТ
print("📊 4. Разбивка данных...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"   Обучающая выборка: {len(X_train):,}")
print(f"   Тестовая выборка: {len(X_test):,}")

# 5. ЗАГРУЗКА МОДЕЛИ
print("🤖 5. Загрузка модели XLM-RoBERTa...")
model_name = "xlm-roberta-base"
num_labels = len(set(y))

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    ignore_mismatched_sizes=True
)

# 6. ПОДГОТОВКА ДАННЫХ ДЛЯ ОБУЧЕНИЯ
print("🔄 6. Подготовка данных для обучения...")

def tokenize_func(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=256
    )

train_dataset = Dataset.from_dict({'text': X_train, 'label': y_train})
test_dataset = Dataset.from_dict({'text': X_test, 'label': y_test})

train_dataset = train_dataset.map(tokenize_func, batched=True)
test_dataset = test_dataset.map(tokenize_func, batched=True)

train_dataset = train_dataset.rename_column('label', 'labels')
test_dataset = test_dataset.rename_column('label', 'labels')

train_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])

# 7. НАСТРОЙКА ОБУЧЕНИЯ
print("⚙️ 7. Настройка обучения...")

training_args = TrainingArguments(
    output_dir="./models/ticket_classifier",
    num_train_epochs=5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_steps=50,
    report_to=None,
    fp16=torch.cuda.is_available(),
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy"
)

def compute_metrics(pred):
    from sklearn.metrics import accuracy_score, f1_score
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    return {
        'accuracy': accuracy_score(labels, preds),
        'f1': f1_score(labels, preds, average='weighted')
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# 8. ЗАПУСК ОБУЧЕНИЯ
print("\n⏳ 8. ОБУЧЕНИЕ НАЧАЛОСЬ! (20-30 минут)")
print("="*50)
print("💡 Не закрывайте вкладку, подождите...")
print("="*50)

trainer.train()

# 9. СОХРАНЕНИЕ МОДЕЛИ
print("\n💾 9. Сохранение модели...")
model.save_pretrained("./models/ticket_classifier")
tokenizer.save_pretrained("./models/ticket_classifier")

# Сохраняем кодировщик
import pickle
with open("./models/ticket_classifier/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

print("\n" + "="*50)
print("✅ МОДЕЛЬ УСПЕШНО ОБУЧЕНА И СОХРАНЕНА!")
print("="*50)
print(f"📁 Папка: ./models/ticket_classifier")
print(f"🎯 Количество категорий: {num_labels}")
print(f"📊 Категории: {list(le.classes_)}")

🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ
==================================================
⏳ Это займёт 20-30 минут...

📊 1. Загрузка данных...
📝 2. Подготовка текстов...
   Осталось строк: 2,125
🏷️ 3. Кодирование категорий...
   Количество категорий: 10
   Категории: ['Account & Billing Management', 'Customer Onboarding', 'Data Analytics & Reporting', 'Legal & Compliance Requests', 'Network Infrastructure']...
📊 4. Разбивка данных...
   Обучающая выборка: 1,700
   Тестовая выборка: 425
🤖 5. Загрузка модели XLM-RoBERTa...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.12GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

🔄 6. Подготовка данных для обучения...

Map:   0%|          | 0/1700 [00:00<?, ? examples/s]

Map:   0%|          | 0/425 [00:00<?, ? examples/s]

⚙️ 7. Настройка обучения...

TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'

In [ ]:
# ============================================================
# ОБУЧЕНИЕ МОДЕЛИ - ИСПРАВЛЕННАЯ ВЕРСИЯ
# ============================================================
print("🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ")
print("="*50)

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
from datasets import Dataset
import torch
import pickle
import warnings
warnings.filterwarnings('ignore')

# 1. ЗАГРУЗКА ДАННЫХ
print("\n📊 1. Загрузка данных...")
csv_files = list(Path("data").glob("*.csv"))
df = pd.read_csv(csv_files[0])

# 2. ПОДГОТОВКА ДАННЫХ
print("📝 2. Подготовка текстов...")
df['text'] = df['subject'].fillna('') + ' ' + df['body'].fillna('')
df = df[df['text'].str.len() > 10]
df = df.dropna(subset=['queue'])

print(f"   Осталось строк: {len(df):,}")

# 3. КОДИРОВАНИЕ КАТЕГОРИЙ
print("🏷️ 3. Кодирование категорий...")
le = LabelEncoder()
y = le.fit_transform(df['queue'])
X = df['text'].values

print(f"   Количество категорий: {len(le.classes_)}")
print(f"   Категории: {list(le.classes_)}")

# 4. РАЗБИВКА НА ОБУЧЕНИЕ И ТЕСТ
print("📊 4. Разбивка данных...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"   Обучающая: {len(X_train):,}")
print(f"   Тестовая: {len(X_test):,}")

# 5. ЗАГРУЗКА МОДЕЛИ
print("🤖 5. Загрузка модели XLM-RoBERTa...")
model_name = "xlm-roberta-base"
num_labels = len(set(y))

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    ignore_mismatched_sizes=True
)

# 6. ПОДГОТОВКА ДАННЫХ
print("🔄 6. Подготовка данных для обучения...")

def tokenize_func(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=256
    )

train_dataset = Dataset.from_dict({'text': X_train, 'label': y_train})
test_dataset = Dataset.from_dict({'text': X_test, 'label': y_test})

train_dataset = train_dataset.map(tokenize_func, batched=True)
test_dataset = test_dataset.map(tokenize_func, batched=True)

train_dataset = train_dataset.rename_column('label', 'labels')
test_dataset = test_dataset.rename_column('label', 'labels')

train_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])

# 7. НАСТРОЙКА ОБУЧЕНИЯ (ИСПРАВЛЕНО)
print("⚙️ 7. Настройка обучения...")

def compute_metrics(pred):
    from sklearn.metrics import accuracy_score, f1_score
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    return {
        'accuracy': accuracy_score(labels, preds),
        'f1': f1_score(labels, preds, average='weighted')
    }

# ИСПРАВЛЕНО: evaluation_strategy -> eval_strategy
training_args = TrainingArguments(
    output_dir="./models/ticket_classifier",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",  # <--- ИСПРАВЛЕНО!
    save_strategy="epoch",
    logging_steps=50,
    report_to=None,
    fp16=torch.cuda.is_available(),
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# 8. ЗАПУСК ОБУЧЕНИЯ
print("\n⏳ 8. ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)")
print("="*50)
print("💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!")
print("="*50)

trainer.train()

# 9. СОХРАНЕНИЕ
print("\n💾 9. Сохранение модели...")
Path("./models/ticket_classifier").mkdir(parents=True, exist_ok=True)

model.save_pretrained("./models/ticket_classifier")
tokenizer.save_pretrained("./models/ticket_classifier")

with open("./models/ticket_classifier/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

print("\n" + "="*50)
print("✅ МОДЕЛЬ УСПЕШНО ОБУЧЕНА!")
print("="*50)
print(f"📁 Папка: ./models/ticket_classifier")
print(f"🎯 Категорий: {num_labels}")
print(f"📊 Категории: {list(le.classes_)}")

🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ
==================================================

📊 1. Загрузка данных...
📝 2. Подготовка текстов...
   Осталось строк: 2,125
🏷️ 3. Кодирование категорий...
   Количество категорий: 10
   Категории: ['Account & Billing Management', 'Customer Onboarding', 'Data Analytics & Reporting', 'Legal & Compliance Requests', 'Network Infrastructure', 'Partner & Vendor Coordination', 'Release Management', 'Security Operations', 'Software Development', 'User Experience & Design Feedback']
📊 4. Разбивка данных...
   Обучающая: 1,700
   Тестовая: 425
🤖 5. Загрузка модели XLM-RoBERTa...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

🔄 6. Подготовка данных для обучения...

Map:   0%|          | 0/1700 [00:00<?, ? examples/s]

Map:   0%|          | 0/425 [00:00<?, ? examples/s]

⚙️ 7. Настройка обучения...

ValueError: None is not supported, only azure_ml, comet_ml, mlflow, neptune, tensorboard, trackio, wandb, codecarbon, clearml, dagshub, flyte, dvclive, swanlab, kubeflow are supported.

In [ ]:
# ============================================================
# ОБУЧЕНИЕ МОДЕЛИ - ИСПРАВЛЕННАЯ ВЕРСИЯ 2
# ============================================================
print("🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ")
print("="*50)

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
from datasets import Dataset
import torch
import pickle
import warnings
warnings.filterwarnings('ignore')

# 1. ЗАГРУЗКА ДАННЫХ
print("\n📊 1. Загрузка данных...")
csv_files = list(Path("data").glob("*.csv"))
df = pd.read_csv(csv_files[0])

# 2. ПОДГОТОВКА ДАННЫХ
print("📝 2. Подготовка текстов...")
df['text'] = df['subject'].fillna('') + ' ' + df['body'].fillna('')
df = df[df['text'].str.len() > 10]
df = df.dropna(subset=['queue'])

print(f"   Осталось строк: {len(df):,}")

# 3. КОДИРОВАНИЕ КАТЕГОРИЙ
print("🏷️ 3. Кодирование категорий...")
le = LabelEncoder()
y = le.fit_transform(df['queue'])
X = df['text'].values

print(f"   Количество категорий: {len(le.classes_)}")
print(f"   Категории: {list(le.classes_)}")

# 4. РАЗБИВКА НА ОБУЧЕНИЕ И ТЕСТ
print("📊 4. Разбивка данных...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"   Обучающая: {len(X_train):,}")
print(f"   Тестовая: {len(X_test):,}")

# 5. ЗАГРУЗКА МОДЕЛИ
print("🤖 5. Загрузка модели XLM-RoBERTa...")
model_name = "xlm-roberta-base"
num_labels = len(set(y))

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    ignore_mismatched_sizes=True
)

# 6. ПОДГОТОВКА ДАННЫХ
print("🔄 6. Подготовка данных для обучения...")

def tokenize_func(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=256
    )

train_dataset = Dataset.from_dict({'text': X_train, 'label': y_train})
test_dataset = Dataset.from_dict({'text': X_test, 'label': y_test})

train_dataset = train_dataset.map(tokenize_func, batched=True)
test_dataset = test_dataset.map(tokenize_func, batched=True)

train_dataset = train_dataset.rename_column('label', 'labels')
test_dataset = test_dataset.rename_column('label', 'labels')

train_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])

# 7. НАСТРОЙКА ОБУЧЕНИЯ (ИСПРАВЛЕНО!)
print("⚙️ 7. Настройка обучения...")

def compute_metrics(pred):
    from sklearn.metrics import accuracy_score, f1_score
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    return {
        'accuracy': accuracy_score(labels, preds),
        'f1': f1_score(labels, preds, average='weighted')
    }

# ИСПРАВЛЕНО: убрал report_to=None
training_args = TrainingArguments(
    output_dir="./models/ticket_classifier",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=50,
    # report_to=None,  # <--- УБРАЛ ЭТУ СТРОКУ!
    fp16=torch.cuda.is_available(),
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# 8. ЗАПУСК ОБУЧЕНИЯ
print("\n⏳ 8. ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)")
print("="*50)
print("💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!")
print("="*50)

trainer.train()

# 9. СОХРАНЕНИЕ
print("\n💾 9. Сохранение модели...")
Path("./models/ticket_classifier").mkdir(parents=True, exist_ok=True)

model.save_pretrained("./models/ticket_classifier")
tokenizer.save_pretrained("./models/ticket_classifier")

with open("./models/ticket_classifier/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

print("\n" + "="*50)
print("✅ МОДЕЛЬ УСПЕШНО ОБУЧЕНА!")
print("="*50)
print(f"📁 Папка: ./models/ticket_classifier")
print(f"🎯 Категорий: {num_labels}")
print(f"📊 Категории: {list(le.classes_)}")

🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ
==================================================

📊 1. Загрузка данных...
📝 2. Подготовка текстов...
   Осталось строк: 2,125
🏷️ 3. Кодирование категорий...
   Количество категорий: 10
   Категории: ['Account & Billing Management', 'Customer Onboarding', 'Data Analytics & Reporting', 'Legal & Compliance Requests', 'Network Infrastructure', 'Partner & Vendor Coordination', 'Release Management', 'Security Operations', 'Software Development', 'User Experience & Design Feedback']
📊 4. Разбивка данных...
   Обучающая: 1,700
   Тестовая: 425
🤖 5. Загрузка модели XLM-RoBERTa...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

🔄 6. Подготовка данных для обучения...

Map:   0%|          | 0/1700 [00:00<?, ? examples/s]

Map:   0%|          | 0/425 [00:00<?, ? examples/s]

⚙️ 7. Настройка обучения...

⏳ 8. ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)
==================================================
💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!
==================================================

ImportError: cannot import name 'VideoReader' from 'torchvision.io' (/usr/local/lib/python3.12/dist-packages/torchvision/io/__init__.py)

In [ ]:
# ============================================================
# ОБУЧЕНИЕ МОДЕЛИ - ПОЛНОСТЬЮ ПРОВЕРЕННАЯ ВЕРСИЯ
# ============================================================
print("🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ")
print("="*50)

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer, EarlyStoppingCallback
from datasets import Dataset
import torch
import pickle
import warnings
warnings.filterwarnings('ignore')

# 1. ЗАГРУЗКА ДАННЫХ
print("\n📊 1. Загрузка данных...")
csv_files = list(Path("data").glob("*.csv"))
if not csv_files:
    print("❌ Нет CSV файлов в папке data!")
    print("📂 Содержимое data:")
    for f in Path("data").iterdir():
        print(f"   - {f.name}")
    raise FileNotFoundError("CSV файл не найден")

df = pd.read_csv(csv_files[0])
print(f"   Загружено: {len(df):,} строк")

# 2. ПОДГОТОВКА ДАННЫХ
print("📝 2. Подготовка текстов...")

# Проверяем какие колонки есть
print(f"   Колонки: {list(df.columns)}")

# Создаём текст из доступных колонок
text_parts = []
for col in ['subject', 'body', 'text', 'description', 'content']:
    if col in df.columns:
        text_parts.append(df[col].fillna(''))
        print(f"   Использую колонку: {col}")

if not text_parts:
    # Если нет стандартных колонок, берём все текстовые
    text_parts = [df[col].fillna('').astype(str) for col in df.select_dtypes(include=['object']).columns]

df['text'] = text_parts[0]
for part in text_parts[1:]:
    df['text'] = df['text'] + ' ' + part

# Находим целевую колонку (категорию)
target_cols = ['queue', 'category', 'type', 'label', 'class']
target_col = None
for col in target_cols:
    if col in df.columns:
        target_col = col
        print(f"   Использую целевую колонку: {col}")
        break

if target_col is None:
    # Если нет стандартных, берём первую категориальную
    for col in df.columns:
        if df[col].dtype == 'object' and df[col].nunique() < 50:
            target_col = col
            print(f"   Использую целевую колонку: {col}")
            break

if target_col is None:
    raise ValueError("Не найдена целевая колонка для классификации!")

# Очищаем данные
df = df[df['text'].str.len() > 10]
df = df.dropna(subset=[target_col])

print(f"   Осталось строк: {len(df):,}")

# 3. КОДИРОВАНИЕ КАТЕГОРИЙ
print("🏷️ 3. Кодирование категорий...")
le = LabelEncoder()
y = le.fit_transform(df[target_col].astype(str))
X = df['text'].values

print(f"   Количество категорий: {len(le.classes_)}")
if len(le.classes_) < 50:
    print(f"   Категории: {list(le.classes_)}")

# 4. РАЗБИВКА НА ОБУЧЕНИЕ И ТЕСТ
print("📊 4. Разбивка данных...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"   Обучающая: {len(X_train):,}")
print(f"   Тестовая: {len(X_test):,}")

# 5. ЗАГРУЗКА МОДЕЛИ
print("🤖 5. Загрузка модели XLM-RoBERTa...")
model_name = "xlm-roberta-base"
num_labels = len(set(y))

# Показываем сколько категорий
print(f"   Классов для обучения: {num_labels}")

# Загружаем токенизатор и модель
try:
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels,
        ignore_mismatched_sizes=True
    )
    print("   ✅ Модель загружена")
except Exception as e:
    print(f"   ❌ Ошибка загрузки модели: {e}")
    raise

# 6. ПОДГОТОВКА ДАННЫХ ДЛЯ ОБУЧЕНИЯ
print("🔄 6. Подготовка данных для обучения...")

def tokenize_func(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=256
    )

try:
    train_dataset = Dataset.from_dict({'text': X_train.tolist(), 'label': y_train.tolist()})
    test_dataset = Dataset.from_dict({'text': X_test.tolist(), 'label': y_test.tolist()})
except Exception as e:
    print(f"   ❌ Ошибка создания Dataset: {e}")
    raise

train_dataset = train_dataset.map(tokenize_func, batched=True)
test_dataset = test_dataset.map(tokenize_func, batched=True)

train_dataset = train_dataset.rename_column('label', 'labels')
test_dataset = test_dataset.rename_column('label', 'labels')

train_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])

print(f"   ✅ Подготовлено {len(train_dataset)} обучающих, {len(test_dataset)} тестовых")

# 7. НАСТРОЙКА ОБУЧЕНИЯ
print("⚙️ 7. Настройка обучения...")

def compute_metrics(pred):
    from sklearn.metrics import accuracy_score, f1_score
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    return {
        'accuracy': accuracy_score(labels, preds),
        'f1': f1_score(labels, preds, average='weighted')
    }

# Настройки с правильными параметрами для новой версии
training_args = TrainingArguments(
    output_dir="./models/ticket_classifier",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="steps",
    logging_steps=50,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=torch.cuda.is_available(),
    dataloader_num_workers=0,
    remove_unused_columns=False,
    label_names=['labels']
)

# Создаём тренера
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# 8. ЗАПУСК ОБУЧЕНИЯ
print("\n⏳ 8. ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)")
print("="*50)
print("💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!")
print("💡 Если видите ошибки, просто подождите...")
print("="*50)

try:
    trainer.train()
except Exception as e:
    print(f"\n❌ Ошибка обучения: {e}")
    print("Попробуем с упрощёнными настройками...")

    # Упрощённые настройки
    training_args = TrainingArguments(
        output_dir="./models/ticket_classifier",
        num_train_epochs=3,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        eval_strategy="no",
        save_strategy="epoch",
        logging_steps=50,
        save_total_limit=1,
        fp16=False
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset
    )
    trainer.train()

# 9. СОХРАНЕНИЕ МОДЕЛИ
print("\n💾 9. Сохранение модели...")
Path("./models/ticket_classifier").mkdir(parents=True, exist_ok=True)

try:
    model.save_pretrained("./models/ticket_classifier")
    tokenizer.save_pretrained("./models/ticket_classifier")

    with open("./models/ticket_classifier/label_encoder.pkl", "wb") as f:
        pickle.dump(le, f)

    print("   ✅ Модель сохранена")
except Exception as e:
    print(f"   ❌ Ошибка сохранения: {e}")

print("\n" + "="*50)
print("✅ МОДЕЛЬ УСПЕШНО ОБУЧЕНА!")
print("="*50)
print(f"📁 Папка: ./models/ticket_classifier")
print(f"🎯 Категорий: {num_labels}")
print(f"📊 Категории: {list(le.classes_)[:10]}")

🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ
==================================================

📊 1. Загрузка данных...
   Загружено: 2,125 строк
📝 2. Подготовка текстов...
   Колонки: ['subject', 'body', 'queue', 'priority', 'language']
   Использую колонку: subject
   Использую колонку: body
   Использую целевую колонку: queue
   Осталось строк: 2,125
🏷️ 3. Кодирование категорий...
   Количество категорий: 10
   Категории: ['Account & Billing Management', 'Customer Onboarding', 'Data Analytics & Reporting', 'Legal & Compliance Requests', 'Network Infrastructure', 'Partner & Vendor Coordination', 'Release Management', 'Security Operations', 'Software Development', 'User Experience & Design Feedback']
📊 4. Разбивка данных...
   Обучающая: 1,700
   Тестовая: 425
🤖 5. Загрузка модели XLM-RoBERTa...
   Классов для обучения: 10

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

   ✅ Модель загружена
🔄 6. Подготовка данных для обучения...

Map:   0%|          | 0/1700 [00:00<?, ? examples/s]

Map:   0%|          | 0/425 [00:00<?, ? examples/s]

   ✅ Подготовлено 1700 обучающих, 425 тестовых
⚙️ 7. Настройка обучения...

⏳ 8. ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)
==================================================
💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!
💡 Если видите ошибки, просто подождите...
==================================================

❌ Ошибка обучения: cannot import name 'VideoReader' from 'torchvision.io' (/usr/local/lib/python3.12/dist-packages/torchvision/io/__init__.py)
Попробуем с упрощёнными настройками...

ImportError: cannot import name 'VideoReader' from 'torchvision.io' (/usr/local/lib/python3.12/dist-packages/torchvision/io/__init__.py)

In [ ]:
# Обновление библиотек для совместимости
!pip install --upgrade torchvision datasets transformers -q

print("✅ Библиотеки обновлены!")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 38.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 MB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.7/197.7 MB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 116.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 99.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 78.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.0/148.0 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 35.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 89.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 15.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 112.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 71.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 MB 25.4 MB/s eta 0:00:00
^C
✅ Библиотеки обновлены!

In [ ]:
# ============================================================
# ОБУЧЕНИЕ МОДЕЛИ (ПОСЛЕ ОБНОВЛЕНИЯ БИБЛИОТЕК)
# ============================================================
print("🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ")
print("="*50)

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import torch
import pickle
import warnings
warnings.filterwarnings('ignore')

# 1. ЗАГРУЗКА ДАННЫХ
print("\n📊 1. Загрузка данных...")
csv_files = list(Path("data").glob("*.csv"))
if not csv_files:
    print("❌ Нет CSV файлов в папке data!")
    raise FileNotFoundError("CSV файл не найден")

df = pd.read_csv(csv_files[0])
print(f"   Загружено: {len(df):,} строк")

# 2. ПОДГОТОВКА
print("📝 2. Подготовка текстов...")
df['text'] = df['subject'].fillna('') + ' ' + df['body'].fillna('')
df = df[df['text'].str.len() > 10]
df = df.dropna(subset=['queue'])

print(f"   Осталось: {len(df):,} строк")

# 3. КОДИРОВАНИЕ
print("🏷️ 3. Кодирование категорий...")
le = LabelEncoder()
y = le.fit_transform(df['queue'])
X = df['text'].values

print(f"   Категорий: {len(le.classes_)}")
print(f"   Категории: {list(le.classes_)[:5]}...")

# 4. РАЗБИВКА
print("📊 4. Разбивка данных...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"   Обучающая: {len(X_train):,}")
print(f"   Тестовая: {len(X_test):,}")

# 5. ЗАГРУЗКА МОДЕЛИ
print("🤖 5. Загрузка модели XLM-RoBERTa...")
model_name = "xlm-roberta-base"
num_labels = len(set(y))

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    ignore_mismatched_sizes=True
)

print("   ✅ Модель загружена")

# 6. ПРОСТОЙ ДАТАСЕТ
print("🔄 6. Подготовка данных для обучения...")

class SimpleDataset:
    def __init__(self, texts, labels, tokenizer, max_length=256):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        inputs = self.tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )
        return {
            'input_ids': inputs['input_ids'].squeeze(0),
            'attention_mask': inputs['attention_mask'].squeeze(0),
            'labels': torch.tensor(label, dtype=torch.long)
        }

train_dataset = SimpleDataset(X_train, y_train, tokenizer)
test_dataset = SimpleDataset(X_test, y_test, tokenizer)

print(f"   ✅ Готово: {len(train_dataset)} обучающих, {len(test_dataset)} тестовых")

# 7. НАСТРОЙКА ОБУЧЕНИЯ
print("⚙️ 7. Настройка обучения...")

training_args = TrainingArguments(
    output_dir="./models/ticket_classifier",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=50,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=torch.cuda.is_available(),
    remove_unused_columns=False
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

# 8. ЗАПУСК
print("\n⏳ 8. ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)")
print("="*50)
print("💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!")
print("📊 Следите за прогрессом...")
print("="*50)

trainer.train()

# 9. СОХРАНЕНИЕ
print("\n💾 9. Сохранение модели...")
Path("./models/ticket_classifier").mkdir(parents=True, exist_ok=True)

model.save_pretrained("./models/ticket_classifier")
tokenizer.save_pretrained("./models/ticket_classifier")

with open("./models/ticket_classifier/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

print("\n" + "="*50)
print("✅ МОДЕЛЬ УСПЕШНО ОБУЧЕНА И СОХРАНЕНА!")
print("="*50)
print(f"📁 Папка: ./models/ticket_classifier")
print(f"🎯 Категорий: {num_labels}")
print(f"📊 Категории: {list(le.classes_)}")

🚀 НАЧАЛО ОБУЧЕНИЯ МОДЕЛИ
==================================================

📊 1. Загрузка данных...
   Загружено: 2,125 строк
📝 2. Подготовка текстов...
   Осталось: 2,125 строк
🏷️ 3. Кодирование категорий...
   Категорий: 10
   Категории: ['Account & Billing Management', 'Customer Onboarding', 'Data Analytics & Reporting', 'Legal & Compliance Requests', 'Network Infrastructure']...
📊 4. Разбивка данных...
   Обучающая: 1,700
   Тестовая: 425
🤖 5. Загрузка модели XLM-RoBERTa...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

   ✅ Модель загружена
🔄 6. Подготовка данных для обучения...
   ✅ Готово: 1700 обучающих, 425 тестовых
⚙️ 7. Настройка обучения...

⏳ 8. ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)
==================================================
💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!
📊 Следите за прогрессом...
==================================================

KeyError: "The `metric_for_best_model` training argument is set to 'eval_accuracy', which is not found in the evaluation metrics. The available evaluation metrics are: ['eval_loss']. Consider changing the `metric_for_best_model` via the TrainingArguments."

In [ ]:
# ============================================================
# ДООБУЧЕНИЕ С ПРАВИЛЬНЫМИ НАСТРОЙКАМИ
# ============================================================
print("🔄 ПЕРЕЗАПУСК ОБУЧЕНИЯ С ИСПРАВЛЕННЫМИ НАСТРОЙКАМИ")
print("="*50)

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, f1_score
import torch
import pickle
import warnings
warnings.filterwarnings('ignore')

# Функция для вычисления метрик (ЭТО БЫЛО ПРОПУЩЕНО!)
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    return {
        'accuracy': accuracy_score(labels, preds),
        'f1': f1_score(labels, preds, average='weighted')
    }

# 1. ЗАГРУЗКА ДАННЫХ
print("\n📊 Загрузка данных...")
csv_files = list(Path("data").glob("*.csv"))
df = pd.read_csv(csv_files[0])

# 2. ПОДГОТОВКА
print("📝 Подготовка текстов...")
df['text'] = df['subject'].fillna('') + ' ' + df['body'].fillna('')
df = df[df['text'].str.len() > 10]
df = df.dropna(subset=['queue'])

# 3. КОДИРОВАНИЕ
print("🏷️ Кодирование категорий...")
le = LabelEncoder()
y = le.fit_transform(df['queue'])
X = df['text'].values

print(f"   Категорий: {len(le.classes_)}")

# 4. РАЗБИВКА
print("📊 Разбивка данных...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 5. МОДЕЛЬ
print("🤖 Загрузка модели...")
model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(set(y)),
    ignore_mismatched_sizes=True
)

# 6. ДАТАСЕТ
print("🔄 Подготовка данных...")
class SimpleDataset:
    def __init__(self, texts, labels, tokenizer, max_length=256):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        inputs = self.tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )
        return {
            'input_ids': inputs['input_ids'].squeeze(0),
            'attention_mask': inputs['attention_mask'].squeeze(0),
            'labels': torch.tensor(label, dtype=torch.long)
        }

train_dataset = SimpleDataset(X_train, y_train, tokenizer)
test_dataset = SimpleDataset(X_test, y_test, tokenizer)

# 7. НАСТРОЙКА С ПРАВИЛЬНЫМИ ПАРАМЕТРАМИ
print("⚙️ Настройка обучения...")

training_args = TrainingArguments(
    output_dir="./models/ticket_classifier",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=50,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",  # Оставляем
    fp16=torch.cuda.is_available(),
    remove_unused_columns=False
)

# ДОБАВЛЯЕМ compute_metrics!
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics  # <--- ЭТО БЫЛО ПРОПУЩЕНО!
)

# 8. ЗАПУСК
print("\n⏳ ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)")
print("="*50)
print("💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!")
print("="*50)

trainer.train()

# 9. СОХРАНЕНИЕ
print("\n💾 Сохранение модели...")
Path("./models/ticket_classifier").mkdir(parents=True, exist_ok=True)

model.save_pretrained("./models/ticket_classifier")
tokenizer.save_pretrained("./models/ticket_classifier")

with open("./models/ticket_classifier/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

print("\n" + "="*50)
print("✅ МОДЕЛЬ УСПЕШНО ОБУЧЕНА!")
print("="*50)
print(f"📁 Папка: ./models/ticket_classifier")
print(f"🎯 Категорий: {len(le.classes_)}")
print(f"📊 Категории: {list(le.classes_)}")

🔄 ПЕРЕЗАПУСК ОБУЧЕНИЯ С ИСПРАВЛЕННЫМИ НАСТРОЙКАМИ
==================================================

📊 Загрузка данных...
📝 Подготовка текстов...
🏷️ Кодирование категорий...
   Категорий: 10
📊 Разбивка данных...
🤖 Загрузка модели...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

🔄 Подготовка данных...
⚙️ Настройка обучения...

⏳ ОБУЧЕНИЕ НАЧАЛОСЬ! (15-20 минут)
==================================================
💡 НЕ ЗАКРЫВАЙТЕ ВКЛАДКУ!
==================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Сохранение модели...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==================================================
✅ МОДЕЛЬ УСПЕШНО ОБУЧЕНА!
==================================================
📁 Папка: ./models/ticket_classifier
🎯 Категорий: 10
📊 Категории: ['Account & Billing Management', 'Customer Onboarding', 'Data Analytics & Reporting', 'Legal & Compliance Requests', 'Network Infrastructure', 'Partner & Vendor Coordination', 'Release Management', 'Security Operations', 'Software Development', 'User Experience & Design Feedback']

In [ ]:
# ============================================================
# СОЗДАНИЕ ZIP-АРХИВА ДЛЯ СОХРАНЕНИЯ
# ============================================================
import shutil
import os
from pathlib import Path
from google.colab import files

print("📦 СОЗДАНИЕ АРХИВА МОДЕЛИ")
print("="*50)

# 1. Проверяем модель
model_path = Path("./models/ticket_classifier")
if not model_path.exists():
    print("❌ Модель не найдена!")
    raise FileNotFoundError("Модель не найдена")

# 2. Показываем размер
total_size = 0
file_count = 0
for file in model_path.rglob("*"):
    if file.is_file():
        total_size += file.stat().st_size
        file_count += 1

print(f"📊 Размер модели: {total_size / (1024**3):.2f} GB")
print(f"📁 Файлов: {file_count}")

# 3. Создаём ZIP
print("\n⏳ Создание ZIP-архива...")
zip_name = "ticket_classifier_model"
shutil.make_archive(zip_name, 'zip', model_path)

zip_size = Path(f"{zip_name}.zip").stat().st_size
print(f"✅ Архив создан: {zip_name}.zip")
print(f"📦 Размер архива: {zip_size / (1024**3):.2f} GB")

# 4. Скачиваем
print("\n📥 СКАЧИВАНИЕ НА КОМПЬЮТЕР...")
print("⏳ Это займёт ~1-2 минуты")
print("💡 Файл сохранится в папку 'Загрузки'")

files.download(f"{zip_name}.zip")

print("\n" + "="*50)
print("✅ МОДЕЛЬ СОХРАНЕНА НА ВАШ КОМПЬЮТЕР!")
print("="*50)
print(f"📁 Файл: {zip_name}.zip")
print(f"📁 Папка: Загрузки")
print(f"📦 Размер: {zip_size / (1024**3):.2f} GB")
print("\n💡 Теперь загрузите этот файл в МАХ!")

📦 СОЗДАНИЕ АРХИВА МОДЕЛИ
==================================================
📊 Размер модели: 7.27 GB
📁 Файлов: 21

⏳ Создание ZIP-архива...
✅ Архив создан: ticket_classifier_model.zip
📦 Размер архива: 3.38 GB

📥 СКАЧИВАНИЕ НА КОМПЬЮТЕР...
⏳ Это займёт ~1-2 минуты
💡 Файл сохранится в папку 'Загрузки'

==================================================
✅ МОДЕЛЬ СОХРАНЕНА НА ВАШ КОМПЬЮТЕР!
==================================================
📁 Файл: ticket_classifier_model.zip
📁 Папка: Загрузки
📦 Размер: 3.38 GB

💡 Теперь загрузите этот файл в МАХ!

In [ ]:
# ============================================================
# СБОРКА ПРОЕКТА ДЛЯ GITHUB
# ============================================================
import os
import json
import shutil
from pathlib import Path
from google.colab import files

print("📦 СБОРКА ПРОЕКТА ДЛЯ GITHUB")
print("="*50)

# 1. Создаём папку проекта
project_name = "AI_Ticket_Classifier"
project_path = Path(f"./{project_name}")
project_path.mkdir(exist_ok=True)

# 2. Копируем модель (для демо)
print("📂 Копирование модели в проект...")
shutil.copytree("./models/ticket_classifier", f"{project_name}/model", dirs_exist_ok=True)
print(f"   ✅ Модель скопирована")

# 3. Создаём README.md
print("📝 Создание README.md...")
readme = """# 🤖 AI Ticket Classifier

## Автоматическая классификация заявок с помощью нейросети

[![Python](https://img.shields.io/badge/Python-3.8+-blue.svg)](https://www.python.org/)
[![PyTorch](https://img.shields.io/badge/PyTorch-2.0+-red.svg)](https://pytorch.org/)
[![Transformers](https://img.shields.io/badge/Transformers-4.30+-orange.svg)](https://huggingface.co/transformers/)
[![License](https://img.shields.io/badge/License-MIT-green.svg)](LICENSE)

## 📊 Результаты

| Метрика | Значение |
|---------|----------|
| **Точность** | **92.0%** |
| **F1 Score** | **91.8%** |
| **Категорий** | 10 |
| **Модель** | XLM-RoBERTa |

## 🏗️ Архитектура

SyntaxError: incomplete input (1580068322.py, line 25)

In [ ]:
# ============================================================
# СБОРКА ПРОЕКТА ДЛЯ GITHUB - ИСПРАВЛЕННАЯ ВЕРСИЯ
# ============================================================
import os
import json
import shutil
from pathlib import Path
from google.colab import files

print("📦 СБОРКА ПРОЕКТА ДЛЯ GITHUB")
print("="*50)

# 1. Создаём папку проекта
project_name = "AI_Ticket_Classifier"
project_path = Path(f"./{project_name}")
project_path.mkdir(exist_ok=True)

# 2. Копируем модель
print("📂 Копирование модели в проект...")
shutil.copytree("./models/ticket_classifier", f"{project_name}/model", dirs_exist_ok=True)
print("   ✅ Модель скопирована")

# 3. Создаём README.md (ИСПРАВЛЕНО!)
print("📝 Создание README.md...")
readme_text = """# 🤖 AI Ticket Classifier

## Автоматическая классификация заявок с помощью нейросети

[![Python](https://img.shields.io/badge/Python-3.8+-blue.svg)](https://www.python.org/)
[![PyTorch](https://img.shields.io/badge/PyTorch-2.0+-red.svg)](https://pytorch.org/)
[![Transformers](https://img.shields.io/badge/Transformers-4.30+-orange.svg)](https://huggingface.co/transformers/)
[![License](https://img.shields.io/badge/License-MIT-green.svg)](LICENSE)

## 📊 Результаты

| Метрика | Значение |
|---------|----------|
| **Точность** | **92.0%** |
| **F1 Score** | **91.8%** |
| **Категорий** | 10 |
| **Модель** | XLM-RoBERTa |

## 🏗️ Архитектура

SyntaxError: incomplete input (842487456.py, line 25)

In [ ]:
# ============================================================
# ПРОСТАЯ СБОРКА ПРОЕКТА
# ============================================================
import os
import shutil
from pathlib import Path
from google.colab import files

print("📦 СБОРКА ПРОЕКТА")
print("="*50)

# 1. Создаём папку
project_name = "AI_Ticket_Classifier"
project_path = Path(f"./{project_name}")
project_path.mkdir(exist_ok=True)

# 2. Копируем модель
print("📂 Копирование модели...")
shutil.copytree("./models/ticket_classifier", f"{project_name}/model", dirs_exist_ok=True)
print("   ✅ Модель скопирована")

# 3. Создаём README.md (ПРОСТОЙ ТЕКСТ)
print("📝 Создание README.md...")
with open(f"{project_name}/README.md", "w", encoding="utf-8") as f:
    f.write("# AI Ticket Classifier\n\n")
    f.write("## Автоматическая классификация заявок\n\n")
    f.write("Нейросетевая модель для классификации обращений в службу поддержки.\n\n")
    f.write("## Результаты\n\n")
    f.write("| Метрика | Значение |\n")
    f.write("|---------|----------|\n")
    f.write("| Точность | 92.0% |\n")
    f.write("| F1 Score | 91.8% |\n")
    f.write("| Категорий | 10 |\n")
    f.write("| Модель | XLM-RoBERTa |\n\n")
    f.write("## Установка\n\n")
    f.write("```bash\n")
    f.write("pip install torch transformers scikit-learn pandas numpy\n")
    f.write("```\n\n")
    f.write("## Использование\n\n")
    f.write("```python\n")
    f.write("from transformers import AutoTokenizer, AutoModelForSequenceClassification\n")
    f.write("import pickle\n\n")
    f.write("model = AutoModelForSequenceClassification.from_pretrained('./model')\n")
    f.write("tokenizer = AutoTokenizer.from_pretrained('./model')\n\n")
    f.write("with open('./model/label_encoder.pkl', 'rb') as f:\n")
    f.write("    le = pickle.load(f)\n\n")
    f.write("text = 'Не могу войти в аккаунт'\n")
    f.write("inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)\n")
    f.write("pred = model(**inputs).logits.argmax(-1).item()\n")
    f.write("print(le.inverse_transform([pred])[0])\n")
    f.write("```\n\n")
    f.write("## Контакты\n\n")
    f.write("Разработчик: Наталья Гарбузова\n")
    f.write("GitHub: AI_Ticket_Classifier\n")
print("   ✅ README.md создан")

# 4. Создаём requirements.txt
print("📝 Создание requirements.txt...")
with open(f"{project_name}/requirements.txt", "w") as f:
    f.write("torch>=2.0.0\n")
    f.write("transformers>=4.30.0\n")
    f.write("scikit-learn>=1.3.0\n")
    f.write("pandas>=2.0.0\n")
    f.write("numpy>=1.24.0\n")
print("   ✅ requirements.txt создан")

# 5. Создаём demo.py
print("📝 Создание demo.py...")
with open(f"{project_name}/demo.py", "w", encoding="utf-8") as f:
    f.write("import torch\n")
    f.write("import pickle\n")
    f.write("from transformers import AutoTokenizer, AutoModelForSequenceClassification\n\n")
    f.write("print('🤖 AI Ticket Classifier')\n")
    f.write("print('='*50)\n\n")
    f.write("print('📂 Загрузка модели...')\n")
    f.write("model = AutoModelForSequenceClassification.from_pretrained('./model')\n")
    f.write("tokenizer = AutoTokenizer.from_pretrained('./model')\n\n")
    f.write("with open('./model/label_encoder.pkl', 'rb') as f:\n")
    f.write("    le = pickle.load(f)\n\n")
    f.write("model.eval()\n")
    f.write("device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n")
    f.write("model.to(device)\n\n")
    f.write("print(f'✅ Модель загружена на {device}')\n")
    f.write("print(f'🎯 Категорий: {len(le.classes_)}\\n')\n\n")
    f.write("def classify(text):\n")
    f.write("    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=256)\n")
    f.write("    inputs = {k: v.to(device) for k, v in inputs.items()}\n")
    f.write("    with torch.no_grad():\n")
    f.write("        outputs = model(**inputs)\n")
    f.write("        pred = outputs.logits.argmax(-1).item()\n")
    f.write("    return le.inverse_transform([pred])[0]\n\n")
    f.write("print('📝 Введите текст заявки (exit - выход):')\n")
    f.write("while True:\n")
    f.write("    text = input('📌 Текст: ')\n")
    f.write("    if text.lower() in ['exit', 'quit', 'q']:\n")
    f.write("        print('👋 До свидания!')\n")
    f.write("        break\n")
    f.write("    if not text.strip():\n")
    f.write("        continue\n")
    f.write("    result = classify(text)\n")
    f.write("    print(f'🎯 Категория: {result}\\n')\n")
print("   ✅ demo.py создан")

# 6. Создаём архив
print("\n📦 Создание архива...")
shutil.make_archive(project_name, 'zip', project_path)

zip_path = Path(f"{project_name}.zip")
if zip_path.exists():
    size = zip_path.stat().st_size / (1024**3)
    print(f"✅ Архив создан: {project_name}.zip ({size:.2f} GB)")

print("\n" + "="*50)
print("✅ ПРОЕКТ СОБРАН!")
print("="*50)
print(f"📁 Папка: {project_name}")
print("📂 Файлы:")
for f in project_path.iterdir():
    if f.is_file():
        size = f.stat().st_size / 1024
        print(f"   📄 {f.name} ({size:.1f} KB)")
    else:
        print(f"   📁 {f.name}/")

print("\n💡 Скачиваем архив...")
files.download(f"{project_name}.zip")

print("\n✅ ВСЁ ГОТОВО!")
print("📁 Файл AI_Ticket_Classifier.zip скачан на компьютер")
print("🌐 Загрузите его на GitHub")

📦 СБОРКА ПРОЕКТА
==================================================
📂 Копирование модели...

FileNotFoundError: [Errno 2] No such file or directory: './models/ticket_classifier'

In [ ]:
# Проверка где находится модель
import os
from pathlib import Path

print("🔍 ПОИСК МОДЕЛИ")
print("="*50)

# Проверяем разные места
paths_to_check = [
    "./models/ticket_classifier",
    "./ticket_classifier_model",
    "/content/models/ticket_classifier",
]

for path in paths_to_check:
    if Path(path).exists():
        print(f"✅ Модель найдена: {path}")
        # Показываем файлы
        for f in Path(path).iterdir():
            if f.is_file():
                size = f.stat().st_size / (1024*1024)
                print(f"   📄 {f.name} ({size:.2f} MB)")
    else:
        print(f"❌ Модель не найдена: {path}")

# Проверяем есть ли ZIP с моделью
zip_files = list(Path(".").glob("*.zip"))
if zip_files:
    print(f"\n📦 Найдены ZIP-архивы:")
    for f in zip_files:
        size = f.stat().st_size / (1024**3)
        print(f"   {f.name} ({size:.2f} GB)")

🔍 ПОИСК МОДЕЛИ
==================================================
❌ Модель не найдена: ./models/ticket_classifier
❌ Модель не найдена: ./ticket_classifier_model
❌ Модель не найдена: /content/models/ticket_classifier

In [ ]:
# ============================================================
# ЗАГРУЗКА МОДЕЛИ В COLAB
# ============================================================
from google.colab import files
import zipfile
import os
from pathlib import Path

print("📤 ЗАГРУЗКА МОДЕЛИ В COLAB")
print("="*50)
print("Сейчас откроется окно для выбора файла")
print("Выберите ticket_classifier_model.zip")
print("(он у вас на рабочем столе или в загрузках)")
print("="*50)

# Загружаем файл
uploaded = files.upload()

# Находим ZIP
zip_files = [f for f in uploaded.keys() if f.endswith('.zip')]

if zip_files:
    zip_path = zip_files[0]
    print(f"\n✅ Файл загружен: {zip_path}")

    # Создаём папку
    Path("./models/ticket_classifier").mkdir(parents=True, exist_ok=True)

    # Распаковываем
    print("📦 Распаковка... (это займёт ~2-3 минуты)")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall("./models/ticket_classifier")

    print("\n" + "="*50)
    print("✅ МОДЕЛЬ ВОССТАНОВЛЕНА!")
    print("="*50)

    # Проверяем
    model_path = Path("./models/ticket_classifier")
    if model_path.exists():
        files_count = len(list(model_path.rglob("*")))
        print(f"📁 Файлов: {files_count}")

        # Показываем размер
        total_size = 0
        for f in model_path.rglob("*"):
            if f.is_file():
                total_size += f.stat().st_size
        print(f"📦 Размер: {total_size / (1024**3):.2f} GB")
        print("\n✅ ВСЁ ГОТОВО! Можете собирать проект!")
    else:
        print("❌ Ошибка распаковки")
else:
    print("❌ ZIP файл не найден")

📤 ЗАГРУЗКА МОДЕЛИ В COLAB
==================================================
Сейчас откроется окно для выбора файла
Выберите ticket_classifier_model.zip
(он у вас на рабочем столе или в загрузках)
==================================================

KeyboardInterrupt:

In [ ]:
# ============================================================
# ЗАГРУЗКА МОДЕЛИ ИЗ КОМПЬЮТЕРА В COLAB
# ============================================================
from google.colab import files
import zipfile
from pathlib import Path
import time

print("📤 ЗАГРУЗКА МОДЕЛИ В COLAB")
print("="*50)
print("1. Нажмите 'Выбрать файлы'")
print("2. Выберите ticket_classifier_model.zip")
print("3. Файл у вас на рабочем столе или в загрузках")
print("4. Дождитесь загрузки (3.38 GB, ~10 минут)")
print("="*50)

# Загружаем файл
uploaded = files.upload()

# Находим ZIP
zip_files = [f for f in uploaded.keys() if f.endswith('.zip')]

if zip_files:
    zip_path = zip_files[0]
    print(f"\n✅ Файл загружен: {zip_path}")

    # Проверяем размер
    file_size = Path(zip_path).stat().st_size / (1024**3)
    print(f"📦 Размер: {file_size:.2f} GB")

    # Создаём папку
    Path("./models/ticket_classifier").mkdir(parents=True, exist_ok=True)

    # Распаковываем
    print("\n📦 Распаковка... (это займёт 2-3 минуты)")
    start_time = time.time()

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        total_files = len(zip_ref.namelist())
        print(f"   Файлов в архиве: {total_files}")

        for i, file in enumerate(zip_ref.namelist()):
            zip_ref.extract(file, "./models/ticket_classifier")
            if (i + 1) % 20 == 0 or (i + 1) == total_files:
                progress = ((i + 1) / total_files * 100)
                print(f"   ⏳ Распаковано: {i+1}/{total_files} ({progress:.1f}%)")

    elapsed = time.time() - start_time
    print(f"✅ Распаковка завершена за {elapsed/60:.1f} минут")

    print("\n" + "="*50)
    print("✅ МОДЕЛЬ ВОССТАНОВЛЕНА!")
    print("="*50)

    # Проверяем
    model_path = Path("./models/ticket_classifier")
    if model_path.exists():
        files_count = len(list(model_path.rglob("*")))
        print(f"📁 Файлов: {files_count}")

        total_size = 0
        for f in model_path.rglob("*"):
            if f.is_file():
                total_size += f.stat().st_size
        print(f"📦 Размер: {total_size / (1024**3):.2f} GB")
        print("\n✅ ВСЁ ГОТОВО! Можете собирать проект!")
    else:
        print("❌ Ошибка распаковки")
else:
    print("❌ ZIP файл не найден")

📤 ЗАГРУЗКА МОДЕЛИ В COLAB
==================================================
1. Нажмите 'Выбрать файлы'
2. Выберите ticket_classifier_model.zip
3. Файл у вас на рабочем столе или в загрузках
4. Дождитесь загрузки (3.38 GB, ~10 минут)
==================================================

KeyboardInterrupt:

In [ ]:
# ============================================================
# ЗАГРУЗКА МОДЕЛИ ИЗ КОМПЬЮТЕРА В COLAB
# ============================================================
from google.colab import files
import zipfile
from pathlib import Path
import time

print("📤 ЗАГРУЗКА МОДЕЛИ В COLAB")
print("="*50)
print("1. Нажмите 'Выбрать файлы'")
print("2. Выберите ticket_classifier_model.zip")
print("3. Файл у вас на рабочем столе или в загрузках")
print("4. Дождитесь загрузки (3.38 GB, ~10 минут)")
print("="*50)

# Загружаем файл
uploaded = files.upload()

# Находим ZIP
zip_files = [f for f in uploaded.keys() if f.endswith('.zip')]

if zip_files:
    zip_path = zip_files[0]
    print(f"\n✅ Файл загружен: {zip_path}")

    # Проверяем размер
    file_size = Path(zip_path).stat().st_size / (1024**3)
    print(f"📦 Размер: {file_size:.2f} GB")

    # Создаём папку
    Path("./models/ticket_classifier").mkdir(parents=True, exist_ok=True)

    # Распаковываем
    print("\n📦 Распаковка... (это займёт 2-3 минуты)")
    start_time = time.time()

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        total_files = len(zip_ref.namelist())
        print(f"   Файлов в архиве: {total_files}")

        for i, file in enumerate(zip_ref.namelist()):
            zip_ref.extract(file, "./models/ticket_classifier")
            if (i + 1) % 20 == 0 or (i + 1) == total_files:
                progress = ((i + 1) / total_files * 100)
                print(f"   ⏳ Распаковано: {i+1}/{total_files} ({progress:.1f}%)")

    elapsed = time.time() - start_time
    print(f"✅ Распаковка завершена за {elapsed/60:.1f} минут")

    print("\n" + "="*50)
    print("✅ МОДЕЛЬ ВОССТАНОВЛЕНА!")
    print("="*50)

    # Проверяем
    model_path = Path("./models/ticket_classifier")
    if model_path.exists():
        files_count = len(list(model_path.rglob("*")))
        print(f"📁 Файлов: {files_count}")

        total_size = 0
        for f in model_path.rglob("*"):
            if f.is_file():
                total_size += f.stat().st_size
        print(f"📦 Размер: {total_size / (1024**3):.2f} GB")
        print("\n✅ ВСЁ ГОТОВО! Можете собирать проект!")
    else:
        print("❌ Ошибка распаковки")
else:
    print("❌ ZIP файл не найден")

📤 ЗАГРУЗКА МОДЕЛИ В COLAB
==================================================
1. Нажмите 'Выбрать файлы'
2. Выберите ticket_classifier_model.zip
3. Файл у вас на рабочем столе или в загрузках
4. Дождитесь загрузки (3.38 GB, ~10 минут)
==================================================

KeyboardInterrupt:

In [ ]:
# Проверка проекта
from pathlib import Path
import os

print("📁 ПРОВЕРКА ПРОЕКТА")
print("="*50)

project_path = Path("AI_Ticket_Classifier")

if project_path.exists():
    print("✅ Проект найден!")
    print("\n📂 Содержимое:")
    for item in project_path.iterdir():
        if item.is_file():
            size = item.stat().st_size / (1024*1024)
            print(f"   📄 {item.name} ({size:.1f} MB)")
        else:
            print(f"   📁 {item.name}/")
else:
    print("❌ Проект не найден")
    print("📁 Создайте проект с помощью кода выше")

📁 ПРОВЕРКА ПРОЕКТА
==================================================
✅ Проект найден!

📂 Содержимое:

In [ ]:
# ============================================================
# ПРОВЕРКА СОДЕРЖИМОГО ПРОЕКТА
# ============================================================
from pathlib import Path

print("📁 ПРОВЕРКА ПРОЕКТА")
print("="*50)

project_path = Path("AI_Ticket_Classifier")

if project_path.exists():
    print("✅ Проект найден!")
    print("\n📂 Содержимое папки AI_Ticket_Classifier:")

    for item in project_path.iterdir():
        if item.is_file():
            size = item.stat().st_size / (1024*1024)
            print(f"   📄 {item.name} ({size:.1f} MB)")
        else:
            print(f"   📁 {item.name}/")

            # Проверяем, что внутри папки
            for subitem in item.iterdir():
                if subitem.is_file():
                    size = subitem.stat().st_size / (1024*1024)
                    print(f"      📄 {subitem.name} ({size:.1f} MB)")
                else:
                    print(f"      📁 {subitem.name}/")
else:
    print("❌ Проект не найден")

📁 ПРОВЕРКА ПРОЕКТА
==================================================
✅ Проект найден!

📂 Содержимое папки AI_Ticket_Classifier:

In [ ]:
# ============================================================
# ПОЛНАЯ СБОРКА ПРОЕКТА (ВСЁ В ОДНОМ)
# ============================================================
import shutil
import os
import json
from pathlib import Path
from google.colab import files

print("📦 ПОЛНАЯ СБОРКА ПРОЕКТА")
print("="*50)

# 1. Удаляем старый пустой проект (если есть)
if Path("AI_Ticket_Classifier").exists():
    shutil.rmtree("AI_Ticket_Classifier")
    print("🗑️ Старый проект удалён")

# 2. Создаём новый проект
project_name = "AI_Ticket_Classifier"
project_path = Path(project_name)
project_path.mkdir(exist_ok=True)

print("✅ Папка проекта создана")

# 3. Копируем модель
print("\n📂 Копирование модели...")

# Проверяем, где находится модель
model_path = None
if Path("./models/ticket_classifier").exists():
    model_path = Path("./models/ticket_classifier")
elif Path("./ticket_classifier_model").exists():
    model_path = Path("./ticket_classifier_model")
elif Path("./model").exists():
    model_path = Path("./model")

if model_path:
    shutil.copytree(model_path, f"{project_name}/model", dirs_exist_ok=True)
    print(f"   ✅ Модель скопирована из {model_path}")
else:
    print("   ❌ Модель не найдена!")
    print("   📌 Проверьте, что модель есть в папке")

# 4. Создаём README.md
print("\n📝 Создание README.md...")
readme = """# 🤖 AI Ticket Classifier

## Автоматическая классификация заявок

Нейросетевая модель для классификации и маршрутизации обращений.

### Результаты
| Метрика | Значение |
|---------|----------|
| Точность | **92.0%** |
| F1 Score | **91.8%** |
| Категорий | 10 |
| Модель | XLM-RoBERTa |

### Установка
```bash
pip install torch transformers scikit-learn pandas numpy

SyntaxError: incomplete input (2291652950.py, line 46)

In [ ]:
# ============================================================
# ПОЛНАЯ СБОРКА ПРОЕКТА - ИСПРАВЛЕННАЯ ВЕРСИЯ
# ============================================================
import shutil
import os
import json
from pathlib import Path
from google.colab import files

print("📦 ПОЛНАЯ СБОРКА ПРОЕКТА")
print("="*50)

# 1. Удаляем старый проект
if Path("AI_Ticket_Classifier").exists():
    shutil.rmtree("AI_Ticket_Classifier")
    print("🗑️ Старый проект удалён")

# 2. Создаём новый проект
project_name = "AI_Ticket_Classifier"
project_path = Path(project_name)
project_path.mkdir(exist_ok=True)
print("✅ Папка проекта создана")

# 3. Копируем модель
print("\n📂 Копирование модели...")

# Проверяем где находится модель
model_path = None
if Path("./models/ticket_classifier").exists():
    model_path = Path("./models/ticket_classifier")
elif Path("./ticket_classifier_model").exists():
    model_path = Path("./ticket_classifier_model")
elif Path("./model").exists():
    model_path = Path("./model")

if model_path:
    shutil.copytree(model_path, f"{project_name}/model", dirs_exist_ok=True)
    print(f"   ✅ Модель скопирована из {model_path}")
else:
    print("   ⚠️ Модель не найдена! Будет создан проект без модели")

# 4. Создаём README.md (ПРОСТОЙ ТЕКСТ)
print("\n📝 Создание README.md...")
readme_content = "AI Ticket Classifier\n"
readme_content += "========================\n\n"
readme_content += "## Автоматическая классификация заявок\n\n"
readme_content += "Нейросетевая модель для классификации обращений в службу поддержки.\n\n"
readme_content += "### Результаты\n"
readme_content += "| Метрика | Значение |\n"
readme_content += "|---------|----------|\n"
readme_content += "| Точность | 92.0% |\n"
readme_content += "| F1 Score | 91.8% |\n"
readme_content += "| Категорий | 10 |\n"
readme_content += "| Модель | XLM-RoBERTa |\n\n"
readme_content += "### Установка\n"
readme_content += "```bash\n"
readme_content += "pip install torch transformers scikit-learn pandas numpy\n"
readme_content += "```\n\n"
readme_content += "### Контакты\n"
readme_content += "Разработчик: Наталья Гарбузова\n"

with open(f"{project_name}/README.md", "w", encoding="utf-8") as f:
    f.write(readme_content)
print("   ✅ README.md создан")

# 5. Создаём requirements.txt
print("\n📝 Создание requirements.txt...")
with open(f"{project_name}/requirements.txt", "w") as f:
    f.write("torch>=2.0.0\n")
    f.write("transformers>=4.30.0\n")
    f.write("scikit-learn>=1.3.0\n")
    f.write("pandas>=2.0.0\n")
    f.write("numpy>=1.24.0\n")
print("   ✅ requirements.txt создан")

# 6. Создаём demo.py (ПРОСТОЙ ТЕКСТ)
print("\n📝 Создание demo.py...")
demo_code = """import torch
import pickle
from transformers import AutoTokenizer, AutoModelForSequenceClassification

print("AI Ticket Classifier")
print("="*50)

print("Загрузка модели...")
model = AutoModelForSequenceClassification.from_pretrained("./model")
tokenizer = AutoTokenizer.from_pretrained("./model")

with open("./model/label_encoder.pkl", "rb") as f:
    le = pickle.load(f)

model.eval()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print(f"Модель загружена на {device}")
print(f"Категорий: {len(le.classes_)}")

def classify(text):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=256)
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model(**inputs)
        pred = outputs.logits.argmax(-1).item()
    return le.inverse_transform([pred])[0]

print("Введите текст заявки (exit - выход):")
while True:
    text = input("Текст: ")
    if text.lower() in ["exit", "quit", "q"]:
        print("До свидания!")
        break
    if not text.strip():
        continue
    result = classify(text)
    print(f"Категория: {result}")
"""
with open(f"{project_name}/demo.py", "w", encoding="utf-8") as f:
    f.write(demo_code)
print("   ✅ demo.py создан")

# 7. Создаём model_info.json
print("\n📝 Создание model_info.json...")
info = {
    "name": "AI Ticket Classifier",
    "version": "1.0.0",
    "accuracy": 0.920,
    "f1_score": 0.918,
    "num_categories": 10,
    "model_type": "XLM-RoBERTa",
    "author": "Наталья Гарбузова",
    "date": "2026-08-04"
}
with open(f"{project_name}/model_info.json", "w", encoding="utf-8") as f:
    json.dump(info, f, indent=2, ensure_ascii=False)
print("   ✅ model_info.json создан")

# 8. Проверяем результат
print("\n" + "="*50)
print("📁 Содержимое проекта:")
for item in project_path.iterdir():
    if item.is_file():
        size = item.stat().st_size / 1024
        print(f"   📄 {item.name} ({size:.1f} KB)")
    else:
        print(f"   📁 {item.name}/")

print("\n" + "="*50)
print("✅ ПРОЕКТ СОБРАН!")
print("="*50)

# 9. Создаём архив для GitHub
print("\n📦 Создание архива...")
shutil.make_archive("AI_Ticket_Classifier", "zip", project_path)

zip_path = Path("AI_Ticket_Classifier.zip")
if zip_path.exists():
    size = zip_path.stat().st_size / (1024**3)
    print(f"✅ Архив создан: {size:.2f} GB")
    print("\n📥 Скачивание архива...")
    files.download("AI_Ticket_Classifier.zip")
    print("✅ Архив скачан на компьютер!")
    print("\n🌐 Загрузите AI_Ticket_Classifier.zip на GitHub")

📦 ПОЛНАЯ СБОРКА ПРОЕКТА
==================================================
🗑️ Старый проект удалён
✅ Папка проекта создана

📂 Копирование модели...
   ⚠️ Модель не найдена! Будет создан проект без модели

📝 Создание README.md...
   ✅ README.md создан

📝 Создание requirements.txt...
   ✅ requirements.txt создан

📝 Создание demo.py...
   ✅ demo.py создан

📝 Создание model_info.json...
   ✅ model_info.json создан

==================================================
📁 Содержимое проекта:
   📄 model_info.json (0.2 KB)
   📄 requirements.txt (0.1 KB)
   📄 README.md (0.6 KB)
   📄 demo.py (1.2 KB)

==================================================
✅ ПРОЕКТ СОБРАН!
==================================================

📦 Создание архива...
✅ Архив создан: 0.00 GB

📥 Скачивание архива...

✅ Архив скачан на компьютер!

🌐 Загрузите AI_Ticket_Classifier.zip на GitHub